// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mq_msg.proto

#ifndef PROTOBUF_mq_5fmsg_2eproto__INCLUDED
#define PROTOBUF_mq_5fmsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace bitmq {
class BasicProperties;
class BasicPropertiesDefaultTypeInternal;
extern BasicPropertiesDefaultTypeInternal _BasicProperties_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_Payload;
class Message_PayloadDefaultTypeInternal;
extern Message_PayloadDefaultTypeInternal _Message_Payload_default_instance_;
}  // namespace bitmq

namespace bitmq {

namespace protobuf_mq_5fmsg_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_mq_5fmsg_2eproto

enum ExchangeType {
  UNKNOWTYPE = 0,
  DIRECT = 1,
  FANOUT = 2,
  TOPIC = 3,
  ExchangeType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ExchangeType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ExchangeType_IsValid(int value);
const ExchangeType ExchangeType_MIN = UNKNOWTYPE;
const ExchangeType ExchangeType_MAX = TOPIC;
const int ExchangeType_ARRAYSIZE = ExchangeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ExchangeType_descriptor();
inline const ::std::string& ExchangeType_Name(ExchangeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ExchangeType_descriptor(), value);
}
inline bool ExchangeType_Parse(
    const ::std::string& name, ExchangeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ExchangeType>(
    ExchangeType_descriptor(), name, value);
}
enum DeliveryMode {
  UNKNOWMODE = 0,
  UNDURABLE = 1,
  DURABLE = 2,
  DeliveryMode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DeliveryMode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DeliveryMode_IsValid(int value);
const DeliveryMode DeliveryMode_MIN = UNKNOWMODE;
const DeliveryMode DeliveryMode_MAX = DURABLE;
const int DeliveryMode_ARRAYSIZE = DeliveryMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* DeliveryMode_descriptor();
inline const ::std::string& DeliveryMode_Name(DeliveryMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    DeliveryMode_descriptor(), value);
}
inline bool DeliveryMode_Parse(
    const ::std::string& name, DeliveryMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DeliveryMode>(
    DeliveryMode_descriptor(), name, value);
}
// ===================================================================

class BasicProperties : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bitmq.BasicProperties) */ {
 public:
  BasicProperties();
  virtual ~BasicProperties();

  BasicProperties(const BasicProperties& from);

  inline BasicProperties& operator=(const BasicProperties& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BasicProperties& default_instance();

  static inline const BasicProperties* internal_default_instance() {
    return reinterpret_cast<const BasicProperties*>(
               &_BasicProperties_default_instance_);
  }

  void Swap(BasicProperties* other);

  // implements Message ----------------------------------------------

  inline BasicProperties* New() const PROTOBUF_FINAL { return New(NULL); }

  BasicProperties* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BasicProperties& from);
  void MergeFrom(const BasicProperties& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BasicProperties* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string routing_key = 3;
  void clear_routing_key();
  static const int kRoutingKeyFieldNumber = 3;
  const ::std::string& routing_key() const;
  void set_routing_key(const ::std::string& value);
  #if LANG_CXX11
  void set_routing_key(::std::string&& value);
  #endif
  void set_routing_key(const char* value);
  void set_routing_key(const char* value, size_t size);
  ::std::string* mutable_routing_key();
  ::std::string* release_routing_key();
  void set_allocated_routing_key(::std::string* routing_key);

  // .bitmq.DeliveryMode delivery_mode = 2;
  void clear_delivery_mode();
  static const int kDeliveryModeFieldNumber = 2;
  ::bitmq::DeliveryMode delivery_mode() const;
  void set_delivery_mode(::bitmq::DeliveryMode value);

  // @@protoc_insertion_point(class_scope:bitmq.BasicProperties)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr routing_key_;
  int delivery_mode_;
  mutable int _cached_size_;
  friend struct  protobuf_mq_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message_Payload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bitmq.Message.Payload) */ {
 public:
  Message_Payload();
  virtual ~Message_Payload();

  Message_Payload(const Message_Payload& from);

  inline Message_Payload& operator=(const Message_Payload& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message_Payload& default_instance();

  static inline const Message_Payload* internal_default_instance() {
    return reinterpret_cast<const Message_Payload*>(
               &_Message_Payload_default_instance_);
  }

  void Swap(Message_Payload* other);

  // implements Message ----------------------------------------------

  inline Message_Payload* New() const PROTOBUF_FINAL { return New(NULL); }

  Message_Payload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message_Payload& from);
  void MergeFrom(const Message_Payload& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message_Payload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string body = 2;
  void clear_body();
  static const int kBodyFieldNumber = 2;
  const ::std::string& body() const;
  void set_body(const ::std::string& value);
  #if LANG_CXX11
  void set_body(::std::string&& value);
  #endif
  void set_body(const char* value);
  void set_body(const char* value, size_t size);
  ::std::string* mutable_body();
  ::std::string* release_body();
  void set_allocated_body(::std::string* body);

  // string valid = 3;
  void clear_valid();
  static const int kValidFieldNumber = 3;
  const ::std::string& valid() const;
  void set_valid(const ::std::string& value);
  #if LANG_CXX11
  void set_valid(::std::string&& value);
  #endif
  void set_valid(const char* value);
  void set_valid(const char* value, size_t size);
  ::std::string* mutable_valid();
  ::std::string* release_valid();
  void set_allocated_valid(::std::string* valid);

  // .bitmq.BasicProperties properties = 1;
  bool has_properties() const;
  void clear_properties();
  static const int kPropertiesFieldNumber = 1;
  const ::bitmq::BasicProperties& properties() const;
  ::bitmq::BasicProperties* mutable_properties();
  ::bitmq::BasicProperties* release_properties();
  void set_allocated_properties(::bitmq::BasicProperties* properties);

  // @@protoc_insertion_point(class_scope:bitmq.Message.Payload)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr body_;
  ::google::protobuf::internal::ArenaStringPtr valid_;
  ::bitmq::BasicProperties* properties_;
  mutable int _cached_size_;
  friend struct  protobuf_mq_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bitmq.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }

  void Swap(Message* other);

  // implements Message ----------------------------------------------

  inline Message* New() const PROTOBUF_FINAL { return New(NULL); }

  Message* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Message_Payload Payload;

  // accessors -------------------------------------------------------

  // .bitmq.Message.Payload payload = 1;
  bool has_payload() const;
  void clear_payload();
  static const int kPayloadFieldNumber = 1;
  const ::bitmq::Message_Payload& payload() const;
  ::bitmq::Message_Payload* mutable_payload();
  ::bitmq::Message_Payload* release_payload();
  void set_allocated_payload(::bitmq::Message_Payload* payload);

  // uint32 offset = 2;
  void clear_offset();
  static const int kOffsetFieldNumber = 2;
  ::google::protobuf::uint32 offset() const;
  void set_offset(::google::protobuf::uint32 value);

  // uint32 length = 3;
  void clear_length();
  static const int kLengthFieldNumber = 3;
  ::google::protobuf::uint32 length() const;
  void set_length(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:bitmq.Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::bitmq::Message_Payload* payload_;
  ::google::protobuf::uint32 offset_;
  ::google::protobuf::uint32 length_;
  mutable int _cached_size_;
  friend struct  protobuf_mq_5fmsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BasicProperties

// string id = 1;
inline void BasicProperties::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BasicProperties::id() const {
  // @@protoc_insertion_point(field_get:bitmq.BasicProperties.id)
  return id_.GetNoArena();
}
inline void BasicProperties::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bitmq.BasicProperties.id)
}
#if LANG_CXX11
inline void BasicProperties::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bitmq.BasicProperties.id)
}
#endif
inline void BasicProperties::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bitmq.BasicProperties.id)
}
inline void BasicProperties::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bitmq.BasicProperties.id)
}
inline ::std::string* BasicProperties::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:bitmq.BasicProperties.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BasicProperties::release_id() {
  // @@protoc_insertion_point(field_release:bitmq.BasicProperties.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BasicProperties::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:bitmq.BasicProperties.id)
}

// .bitmq.DeliveryMode delivery_mode = 2;
inline void BasicProperties::clear_delivery_mode() {
  delivery_mode_ = 0;
}
inline ::bitmq::DeliveryMode BasicProperties::delivery_mode() const {
  // @@protoc_insertion_point(field_get:bitmq.BasicProperties.delivery_mode)
  return static_cast< ::bitmq::DeliveryMode >(delivery_mode_);
}
inline void BasicProperties::set_delivery_mode(::bitmq::DeliveryMode value) {
  
  delivery_mode_ = value;
  // @@protoc_insertion_point(field_set:bitmq.BasicProperties.delivery_mode)
}

// string routing_key = 3;
inline void BasicProperties::clear_routing_key() {
  routing_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BasicProperties::routing_key() const {
  // @@protoc_insertion_point(field_get:bitmq.BasicProperties.routing_key)
  return routing_key_.GetNoArena();
}
inline void BasicProperties::set_routing_key(const ::std::string& value) {
  
  routing_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bitmq.BasicProperties.routing_key)
}
#if LANG_CXX11
inline void BasicProperties::set_routing_key(::std::string&& value) {
  
  routing_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bitmq.BasicProperties.routing_key)
}
#endif
inline void BasicProperties::set_routing_key(const char* value) {
  
  routing_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bitmq.BasicProperties.routing_key)
}
inline void BasicProperties::set_routing_key(const char* value, size_t size) {
  
  routing_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bitmq.BasicProperties.routing_key)
}
inline ::std::string* BasicProperties::mutable_routing_key() {
  
  // @@protoc_insertion_point(field_mutable:bitmq.BasicProperties.routing_key)
  return routing_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BasicProperties::release_routing_key() {
  // @@protoc_insertion_point(field_release:bitmq.BasicProperties.routing_key)
  
  return routing_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BasicProperties::set_allocated_routing_key(::std::string* routing_key) {
  if (routing_key != NULL) {
    
  } else {
    
  }
  routing_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), routing_key);
  // @@protoc_insertion_point(field_set_allocated:bitmq.BasicProperties.routing_key)
}

// -------------------------------------------------------------------

// Message_Payload

// .bitmq.BasicProperties properties = 1;
inline bool Message_Payload::has_properties() const {
  return this != internal_default_instance() && properties_ != NULL;
}
inline void Message_Payload::clear_properties() {
  if (GetArenaNoVirtual() == NULL && properties_ != NULL) delete properties_;
  properties_ = NULL;
}
inline const ::bitmq::BasicProperties& Message_Payload::properties() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.Payload.properties)
  return properties_ != NULL ? *properties_
                         : *::bitmq::BasicProperties::internal_default_instance();
}
inline ::bitmq::BasicProperties* Message_Payload::mutable_properties() {
  
  if (properties_ == NULL) {
    properties_ = new ::bitmq::BasicProperties;
  }
  // @@protoc_insertion_point(field_mutable:bitmq.Message.Payload.properties)
  return properties_;
}
inline ::bitmq::BasicProperties* Message_Payload::release_properties() {
  // @@protoc_insertion_point(field_release:bitmq.Message.Payload.properties)
  
  ::bitmq::BasicProperties* temp = properties_;
  properties_ = NULL;
  return temp;
}
inline void Message_Payload::set_allocated_properties(::bitmq::BasicProperties* properties) {
  delete properties_;
  properties_ = properties;
  if (properties) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:bitmq.Message.Payload.properties)
}

// string body = 2;
inline void Message_Payload::clear_body() {
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message_Payload::body() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.Payload.body)
  return body_.GetNoArena();
}
inline void Message_Payload::set_body(const ::std::string& value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bitmq.Message.Payload.body)
}
#if LANG_CXX11
inline void Message_Payload::set_body(::std::string&& value) {
  
  body_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bitmq.Message.Payload.body)
}
#endif
inline void Message_Payload::set_body(const char* value) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bitmq.Message.Payload.body)
}
inline void Message_Payload::set_body(const char* value, size_t size) {
  
  body_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bitmq.Message.Payload.body)
}
inline ::std::string* Message_Payload::mutable_body() {
  
  // @@protoc_insertion_point(field_mutable:bitmq.Message.Payload.body)
  return body_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message_Payload::release_body() {
  // @@protoc_insertion_point(field_release:bitmq.Message.Payload.body)
  
  return body_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message_Payload::set_allocated_body(::std::string* body) {
  if (body != NULL) {
    
  } else {
    
  }
  body_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), body);
  // @@protoc_insertion_point(field_set_allocated:bitmq.Message.Payload.body)
}

// string valid = 3;
inline void Message_Payload::clear_valid() {
  valid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message_Payload::valid() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.Payload.valid)
  return valid_.GetNoArena();
}
inline void Message_Payload::set_valid(const ::std::string& value) {
  
  valid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bitmq.Message.Payload.valid)
}
#if LANG_CXX11
inline void Message_Payload::set_valid(::std::string&& value) {
  
  valid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bitmq.Message.Payload.valid)
}
#endif
inline void Message_Payload::set_valid(const char* value) {
  
  valid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bitmq.Message.Payload.valid)
}
inline void Message_Payload::set_valid(const char* value, size_t size) {
  
  valid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bitmq.Message.Payload.valid)
}
inline ::std::string* Message_Payload::mutable_valid() {
  
  // @@protoc_insertion_point(field_mutable:bitmq.Message.Payload.valid)
  return valid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message_Payload::release_valid() {
  // @@protoc_insertion_point(field_release:bitmq.Message.Payload.valid)
  
  return valid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message_Payload::set_allocated_valid(::std::string* valid) {
  if (valid != NULL) {
    
  } else {
    
  }
  valid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valid);
  // @@protoc_insertion_point(field_set_allocated:bitmq.Message.Payload.valid)
}

// -------------------------------------------------------------------

// Message

// .bitmq.Message.Payload payload = 1;
inline bool Message::has_payload() const {
  return this != internal_default_instance() && payload_ != NULL;
}
inline void Message::clear_payload() {
  if (GetArenaNoVirtual() == NULL && payload_ != NULL) delete payload_;
  payload_ = NULL;
}
inline const ::bitmq::Message_Payload& Message::payload() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.payload)
  return payload_ != NULL ? *payload_
                         : *::bitmq::Message_Payload::internal_default_instance();
}
inline ::bitmq::Message_Payload* Message::mutable_payload() {
  
  if (payload_ == NULL) {
    payload_ = new ::bitmq::Message_Payload;
  }
  // @@protoc_insertion_point(field_mutable:bitmq.Message.payload)
  return payload_;
}
inline ::bitmq::Message_Payload* Message::release_payload() {
  // @@protoc_insertion_point(field_release:bitmq.Message.payload)
  
  ::bitmq::Message_Payload* temp = payload_;
  payload_ = NULL;
  return temp;
}
inline void Message::set_allocated_payload(::bitmq::Message_Payload* payload) {
  delete payload_;
  payload_ = payload;
  if (payload) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:bitmq.Message.payload)
}

// uint32 offset = 2;
inline void Message::clear_offset() {
  offset_ = 0u;
}
inline ::google::protobuf::uint32 Message::offset() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.offset)
  return offset_;
}
inline void Message::set_offset(::google::protobuf::uint32 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:bitmq.Message.offset)
}

// uint32 length = 3;
inline void Message::clear_length() {
  length_ = 0u;
}
inline ::google::protobuf::uint32 Message::length() const {
  // @@protoc_insertion_point(field_get:bitmq.Message.length)
  return length_;
}
inline void Message::set_length(::google::protobuf::uint32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:bitmq.Message.length)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace bitmq

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bitmq::ExchangeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bitmq::ExchangeType>() {
  return ::bitmq::ExchangeType_descriptor();
}
template <> struct is_proto_enum< ::bitmq::DeliveryMode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bitmq::DeliveryMode>() {
  return ::bitmq::DeliveryMode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mq_5fmsg_2eproto__INCLUDED
