threadpool:threadpool.cpp
	g++ -std=c++11 $^ -o $@ -lpthread
packaged_task:package_task.cc
	g++ -std=c++11 $^ -o $@ -lpthread
promise:promise.cc
	g++ -std=c++11 $^ -o $@ -lpthread
async:async.cc
	g++ -std=c++11 $^ -o $@ -lpthread